<?php

declare(strict_types=1);

namespace Michalsn\CodeIgniterModuleManager\Services;

use CodeIgniter\I18n\Time;
use Config\Autoload;
use Exception;
use Michalsn\CodeIgniterModuleManager\Exceptions\ModuleException;

class AutoloadManager
{
    private readonly string $autoloadFilePath;

    public function __construct()
    {
        // Store generated PSR-4 array cache file in writable directory
        $this->autoloadFilePath = WRITEPATH . 'modules_psr4.php';
    }

    /**
     * Regenerate the modules autoload file
     * Call this whenever modules are enabled/disabled
     *
     * @param array $enabledModules Array of modules with 'namespace' and 'path' keys
     */
    public function regenerateAutoloadFile(array $enabledModules): bool
    {
        try {
            // If no modules are enabled, delete the autoload file
            if ($enabledModules === []) {
                return $this->deleteAutoloadFile();
            }

            $content = $this->generateAutoloadContent($enabledModules);

            // Write atomically using temp file to prevent partial writes
            $tempFile = $this->autoloadFilePath . '.tmp';

            if (file_put_contents($tempFile, $content) === false) {
                throw ModuleException::forFailedToWriteTempAutoloadFile();
            }

            if (! rename($tempFile, $this->autoloadFilePath)) {
                @unlink($tempFile);

                throw ModuleException::forFailedToRenameTempAutoloadFile();
            }

            // Clear opcode cache if available
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($this->autoloadFilePath, true);
            }

            return true;
        } catch (Exception $e) {
            throw ModuleException::forFailedToRegenerateAutoload($e->getMessage());
        }
    }

    /**
     * Generate the content for the PSR-4 array cache file
     */
    private function generateAutoloadContent(array $enabledModules): string
    {
        $timestamp = Time::now()->toDateTimeString();

        $content = "<?php\n";
        $content .= "/**\n";
        $content .= " * Modules PSR-4 Cache\n";
        $content .= " *\n";
        $content .= " * This file is auto-generated by CodeIgniter Module Manager.\n";
        $content .= " * DO NOT EDIT MANUALLY - changes will be overwritten.\n";
        $content .= " *\n";
        $content .= " * Generated: {$timestamp}\n";
        $content .= " */\n\n";

        // Load bundled autoloaders first (before PSR-4 mappings)
        foreach ($enabledModules as $module) {
            if (! empty($module['has_bundled_deps']) && ! empty($module['path'])) {
                // Path points to src/, vendor is in parent directory
                $vendorAutoload = dirname((string) $module['path']) . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
                $autoloadPath   = $this->escapePhpString($vendorAutoload);

                $content .= "if (file_exists('{$autoloadPath}')) {\n";
                $content .= "    require_once '{$autoloadPath}';\n";
                $content .= "}\n\n";
            }
        }

        // Return PSR-4 mappings
        $content .= "return [\n";

        foreach ($enabledModules as $module) {
            if (empty($module['namespace']) || empty($module['path'])) {
                continue;
            }

            // Validate that the path exists
            if (! is_dir($module['path'])) {
                log_message('warning', "Module path does not exist: {$module['path']}");

                continue;
            }

            $namespace = $this->escapePhpString($module['namespace']);
            $path      = $this->escapePhpString($module['path']);

            $content .= "    '{$namespace}' => '{$path}',\n";
        }

        return $content . "];\n";
    }

    /**
     * Escape a string for safe use in PHP code
     */
    private function escapePhpString(string $string): string
    {
        return addslashes($string);
    }

    /**
     * Get the path to the autoload file
     */
    public function getAutoloadFilePath(): string
    {
        return $this->autoloadFilePath;
    }

    /**
     * Check if autoload file exists
     */
    public function autoloadFileExists(): bool
    {
        return file_exists($this->autoloadFilePath);
    }

    /**
     * Delete the autoload file (when no modules enabled)
     */
    public function deleteAutoloadFile(): bool
    {
        if ($this->autoloadFileExists()) {
            if (! unlink($this->autoloadFilePath)) {
                throw ModuleException::forFailedToDeleteAutoloadFile();
            }

            // Clear opcode cache if available
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($this->autoloadFilePath, true);
            }
        }

        return true;
    }

    /**
     * Check if a specific namespace is registered
     */
    public function isModuleRegistered(string $namespace): bool
    {
        $psr4 = config(Autoload::class)->psr4;

        return isset($psr4[$namespace]);
    }
}
